### ISSUE TITLE
More specific URLs for each step?

### ISSUE THREAD

**Issue by slothbear** [nerdcave/rails-multistep-form#9]
In the example app, each step (after the first `/new`) has the same URL, `/products`. I've been trying to add a name for each step, so perhaps the Product example might go through:

    products/initial (instead of /new)
    products/price
    products/availability

I tried to add routes to `products#create` for the new URLs, but I couldn't figure out how to step to them. Is this URL scheme something that could work with this library? Many thanks!

**Comment by nerdcave** [comment]
The url is ```/products``` because that's where the form is submitting to fire ```create```, which then renders instead of redirects (so the url doesn't change from ```/products```). This same thing happens in rails when you submit a form that has an error, so it's a common quirk.

If you want the URL to change, you either need to 1) redirect instead of render (which can get complicated because you lose state) or 2) change the URL with Javascript (http://stackoverflow.com/questions/3338642/updating-address-bar-with-new-url-without-hash-or-reloading-the-page).

As for the URL itself, I would just add a step/:step route to the end so it looks like this:
```
/products/new/step/1
/products/new/step/2
```

Or even just pass it in as query param:
```
/products/new?step=1
/products/new?step=2
```

If you change line 13 in model_wizard.rb to ```@object.current_step = @params[:step].to_i``` it'll go to the step you pass in. That should at least give you a starting point.

**Comment by slothbear** [comment]
Sounds good! Thanks for looking into it for me – much appreciated.
